More complicated NOTICE checking logic, which first looks for a cached NOTICE, then uses the generated one

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -96,4 +96,38 @@ fossa-check-notice:
     - if: $FOSSA_API_KEY
 
   script:
-    - fossa-compare-notices NOTICE fossa-output/generated-clean-NOTICE
+    # Use a cached NOTICE if available, otherwise use a generated one
+    - |
+      if [ -e fossa-output/cached-NOTICE ]; then
+        fossaGeneratedNotice=fossa-output/cached-NOTICE;
+
+      elif [ -e fossa-output/generated-clean-NOTICE ]; then
+        fossaGeneratedNotice=fossa-output/generated-clean-NOTICE
+
+      else
+        echo "Couldn't find either a cached-NOTICE or generated-clean-NOTICE in the fossa-output/ directory"
+        echo
+        echo "At least one of these should have been generated by a previous job stage (fossa-analyze) and stored"
+        echo "as an artifact. Something must be wrong in the CI setup"
+        exit 1
+      fi
+
+      echo "Comparing with $fossaGeneratedNotice"
+
+    # If the comparison finds differences, let the user know what to do next
+    - |
+      if ! fossa-compare-notices NOTICE $fossaGeneratedNotice; then
+        echo --------------------------------------------------------------------------------
+        echo "There are differences in the NOTICE file"
+        echo "Please review these differences, and if they look appropriate based on your"
+        echo "changes, update the committed NOTICE file"
+        echo "--------------------
+        echo "If you make changes to the NOTICE file (and only the NOTICE file), you can"
+        echo "re-run this single stage of the pipeline alone rather than the whole pipeline"
+        echo "One way to achieve this:"
+        echo "$ wget -O NOTICE '${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/raw/${fossaGeneratedNotice}?inline=false'"
+        echo "$ git commit -m 'Updating NOTICE'"
+        echo "$ git push -o ci.skip"
+        echo "Then retry this job"
+        exit 1
+      fi
